package com.Clinacuity;
public class Main {

    public static void main(String[] args) {
        //Sha-384
        System.out.println("HashCode Generated by SHA-384 for: ");

        String s1 = "hello world";
        System.out.println("\n" + s1 + " : " + Sha384Hashing.encryptThisString(s1));

        //SHA-384 with Salt
        byte[] salt = Sha384withSalt.getSalt();
        String String1 = Sha384withSalt.getSecureString("String1", salt);
        String String2 = Sha384withSalt.getSecureString("String2", salt);
        System.out.println(" String 1 + salt -> " + String1);
        System.out.println(" Password 2 -> " + String2);
        if (String1.equals(String2)) {
            System.out.println("passwords are equal");
        }
    }
}
